#!/usr/bin/env python3
"""PV Forge v0.2.

Renderer-neutral build tooling for The Prismatic Veil / PriZim.

Current jobs:
- validate canonical Prismel active-turn registration/cadence JSON
- generate the Phaser adapter module from that neutral data
- optionally analyze PNG alpha silhouettes (requires Pillow)

Usage:
    python tools/pv_forge/pv_forge.py check
    python tools/pv_forge/pv_forge.py sync
    python tools/pv_forge/pv_forge.py analyze
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
DATA_PATH = ROOT / "pv-data" / "animations" / "prismel_active_turn.registration.json"
GENERATED_PATH = ROOT / "src" / "generated" / "prismelActiveTurnRegistration.js"

READY = [f"prismel_ready_{i}" for i in range(1, 7)]
ATTACK = [f"prismel_attack_{i}" for i in range(1, 7)]
REQUIRED_FRAMES = READY + ATTACK
MATERIAL_CUES = ("shimmer", "staffEmerges", "staffDraw", "staffLock")


class ForgeError(RuntimeError):
    pass


def load_data() -> dict[str, Any]:
    try:
        return json.loads(DATA_PATH.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ForgeError(f"Missing canonical data: {DATA_PATH}") from exc
    except json.JSONDecodeError as exc:
        raise ForgeError(f"Invalid JSON in {DATA_PATH}: {exc}") from exc


def validate(data: dict[str, Any]) -> None:
    if data.get("schemaVersion") != 1:
        raise ForgeError("schemaVersion must be 1")
    if data.get("id") != "prismel_active_turn":
        raise ForgeError("id must be prismel_active_turn")

    frames = data.get("frames")
    if not isinstance(frames, dict):
        raise ForgeError("frames must be an object")

    missing = [key for key in REQUIRED_FRAMES if key not in frames]
    extra = [key for key in frames if key not in REQUIRED_FRAMES]
    if missing:
        raise ForgeError(f"Missing frames: {', '.join(missing)}")
    if extra:
        raise ForgeError(f"Unexpected frames: {', '.join(extra)}")

    for key in REQUIRED_FRAMES:
        entry = frames[key]
        if not isinstance(entry, dict):
            raise ForgeError(f"{key} must be an object")
        for field in ("scale", "x", "y"):
            if field not in entry or not isinstance(entry[field], (int, float)):
                raise ForgeError(f"{key}.{field} must be numeric")
        scale = float(entry["scale"])
        if not math.isfinite(scale) or not 0.75 <= scale <= 1.25:
            raise ForgeError(f"{key}.scale out of safe range: {scale}")
        for field in ("x", "y"):
            value = float(entry[field])
            if not math.isfinite(value) or abs(value) > 32:
                raise ForgeError(f"{key}.{field} out of safe range: {value}")

    material = data.get("materialization")
    if not isinstance(material, dict):
        raise ForgeError("materialization must be an object")
    frame_holds = material.get("frameHoldMs")
    if not isinstance(frame_holds, list) or len(frame_holds) != len(READY):
        raise ForgeError("materialization.frameHoldMs must contain six values")
    for i, value in enumerate(frame_holds, start=1):
        if not isinstance(value, (int, float)) or not 60 <= value <= 700:
            raise ForgeError(f"materialization.frameHoldMs[{i - 1}] must be between 60 and 700 ms")

    cues = material.get("cueFrames")
    if not isinstance(cues, dict):
        raise ForgeError("materialization.cueFrames must be an object")
    missing_cues = [cue for cue in MATERIAL_CUES if cue not in cues]
    extra_cues = [cue for cue in cues if cue not in MATERIAL_CUES]
    if missing_cues:
        raise ForgeError(f"Missing materialization cues: {', '.join(missing_cues)}")
    if extra_cues:
        raise ForgeError(f"Unexpected materialization cues: {', '.join(extra_cues)}")
    for cue in MATERIAL_CUES:
        frame = cues[cue]
        if not isinstance(frame, int) or not 1 <= frame <= len(READY):
            raise ForgeError(f"materialization.cueFrames.{cue} must be an integer from 1 to 6")

    transition = data.get("transition", {})
    for field in ("readyToAttackHoldMs", "attackStartFrameMs", "attackReleaseFrameMs"):
        value = transition.get(field)
        if not isinstance(value, (int, float)) or not 40 <= value <= 500:
            raise ForgeError(f"transition.{field} must be between 40 and 500 ms")


def generate_module(data: dict[str, Any]) -> str:
    frames = data["frames"]
    material = data["materialization"]
    transition = data["transition"]
    lines = [
        "// AUTO-GENERATED by tools/pv_forge/pv_forge.py",
        "// Canonical source: pv-data/animations/prismel_active_turn.registration.json",
        "// Do not hand-edit this file. Run: python tools/pv_forge/pv_forge.py sync",
        "",
        "export const PRISMEL_FRAME_REGISTRATION = Object.freeze({",
    ]
    for key in REQUIRED_FRAMES:
        entry = frames[key]
        lines.append(
            f"  {key}: Object.freeze({{ scale: {float(entry['scale']):.3f}, "
            f"x: {int(entry['x'])}, y: {int(entry['y'])} }}),"
        )
    lines.extend([
        "});",
        "",
        "export const PRISMEL_MATERIALIZATION = Object.freeze({",
        "  frameHoldMs: Object.freeze([" + ", ".join(str(int(v)) for v in material["frameHoldMs"]) + "]),",
        "  cueFrames: Object.freeze({",
    ])
    for cue in MATERIAL_CUES:
        comma = "," if cue != MATERIAL_CUES[-1] else ""
        lines.append(f"    {cue}: {int(material['cueFrames'][cue])}{comma}")
    lines.extend([
        "  })",
        "});",
        "",
        "export const PRISMEL_ATTACK_TRANSITION = Object.freeze({",
        f"  readyToAttackHoldMs: {int(transition['readyToAttackHoldMs'])},",
        f"  attackStartFrameMs: {int(transition['attackStartFrameMs'])},",
        f"  attackReleaseFrameMs: {int(transition['attackReleaseFrameMs'])}",
        "});",
        "",
    ])
    return "\n".join(lines)


def weighted_quantile(values: list[int], total: int, q: float) -> int:
    goal = total * q
    acc = 0
    for index, value in enumerate(values):
        acc += value
        if acc >= goal:
            return index
    return max(0, len(values) - 1)


def analyze_pngs(data: dict[str, Any]) -> dict[str, Any]:
    try:
        from PIL import Image
    except ImportError as exc:
        raise ForgeError(
            "PNG analysis requires Pillow. Install with: python -m pip install Pillow"
        ) from exc

    asset_root = ROOT / str(data["assetRoot"])
    results: dict[str, Any] = {}

    for key in REQUIRED_FRAMES:
        path = asset_root / f"{key}.png"
        if not path.exists():
            raise ForgeError(f"Missing PNG: {path}")

        image = Image.open(path).convert("RGBA")
        width, height = image.size
        pixels = image.getchannel("A").load()

        row_mass: list[int] = []
        total = 0
        for y in range(height):
            mass = 0
            for x in range(width):
                alpha = int(pixels[x, y])
                if alpha > 18:
                    mass += alpha
            row_mass.append(mass)
            total += mass

        if total <= 0:
            raise ForgeError(f"{key} contains no visible alpha")

        top = weighted_quantile(row_mass, total, 0.020)
        bottom = weighted_quantile(row_mass, total, 0.993)
        body_height = max(1, bottom - top + 1)
        lower_start = max(top, int(bottom - body_height * 0.13))

        sum_x = 0.0
        sum_w = 0.0
        for y in range(lower_start, min(height - 1, bottom) + 1):
            for x in range(width):
                alpha = int(pixels[x, y])
                if alpha > 42:
                    sum_x += x * alpha
                    sum_w += alpha

        anchor_x = sum_x / sum_w if sum_w else width * 0.5
        results[key] = {
            "width": width,
            "height": height,
            "bodyTop": top,
            "bodyBottom": bottom,
            "bodyHeight": body_height,
            "anchorX": round(anchor_x, 3),
            "anchorY": min(height, bottom + 1),
        }

    heights = sorted(entry["bodyHeight"] for entry in results.values())
    mid = len(heights) // 2
    median = heights[mid] if len(heights) % 2 else (heights[mid - 1] + heights[mid]) / 2

    for entry in results.values():
        entry["suggestedBodyScale"] = round(median / entry["bodyHeight"], 5)

    return {
        "schemaVersion": 1,
        "source": str(data["assetRoot"]),
        "medianBodyHeight": median,
        "frames": results,
    }


def command_check() -> None:
    data = load_data()
    validate(data)
    expected = generate_module(data)
    if not GENERATED_PATH.exists():
        raise ForgeError(f"Missing generated adapter: {GENERATED_PATH}")
    actual = GENERATED_PATH.read_text(encoding="utf-8")
    if actual != expected:
        raise ForgeError(
            "Generated Phaser adapter is stale. Run: python tools/pv_forge/pv_forge.py sync"
        )
    print("PV Forge check OK: canonical registration/cadence data and Phaser adapter are in sync.")


def command_sync() -> None:
    data = load_data()
    validate(data)
    GENERATED_PATH.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_PATH.write_text(generate_module(data), encoding="utf-8")
    print(f"Wrote {GENERATED_PATH.relative_to(ROOT)}")


def command_analyze(output: str | None) -> None:
    data = load_data()
    validate(data)
    report = analyze_pngs(data)
    text = json.dumps(report, indent=2) + "\n"
    if output:
        path = ROOT / output
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"Wrote {path.relative_to(ROOT)}")
    else:
        print(text, end="")


def main() -> int:
    parser = argparse.ArgumentParser(description="PV Forge / PriZim")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("check", help="validate canonical data and generated adapter")
    sub.add_parser("sync", help="generate renderer adapter from canonical data")
    analyze = sub.add_parser("analyze", help="analyze Prismel PNG alpha registration")
    analyze.add_argument("--output", default=None, help="optional repo-relative JSON output path")
    args = parser.parse_args()

    try:
        if args.command == "check":
            command_check()
        elif args.command == "sync":
            command_sync()
        elif args.command == "analyze":
            command_analyze(args.output)
        return 0
    except ForgeError as exc:
        print(f"PV Forge error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
