(function(){'use strict';
const BASE='./assets/boxedwine-jit/',SHELL=BASE+'boxedwine-shell.js',ENGINE=BASE+'boxedwine.js',ROOT='fullWine1.7.55-v8.zip',APP='userapp.zip',TRACE_KEY='mobmugen-f105-trace';
const zipInput=document.getElementById('zipInput'),setup=document.getElementById('setup'),prep=document.getElementById('prepDiag'),diag=document.getElementById('diag'),state=document.getElementById('runtimeState'),canvas=document.getElementById('canvas'),copyBtn=document.getElementById('copyTrace');
const controls=document.getElementById('controls'),ctrlToggle=document.getElementById('ctrlToggle'),debugToggle=document.getElementById('debugToggle'),diagInlineToggle=document.getElementById('diagInlineToggle'),diagWrap=document.getElementById('diagWrap'),gamepadNote=document.getElementById('gamepadNote'),fpsBadge=document.getElementById('fpsBadge');
let lines=[],bootStarted=false,leanBlob=null,exePath='',exeDir='',rafLast=0,rafCount=0,drawCount=0,drawLast=0,engineDead=false,startedAt=0;
function status(s){state.textContent=s}
function log(s){s=String(s);lines.push(s);if(lines.length>700)lines.shift();diag.textContent=lines.join('\n');diag.scrollTop=diag.scrollHeight;try{localStorage.setItem(TRACE_KEY,lines.join('\n'))}catch(_){} }
function fail(e){status('FAILED');log('F10.5 ERROR · '+((e&&e.stack)||e));prep.textContent='FAILED · '+((e&&e.message)||e);setup.classList.remove('hide')}
window.addEventListener('error',e=>log('JS ERROR · '+e.message+' @ '+e.filename+':'+e.lineno));window.addEventListener('unhandledrejection',e=>log('PROMISE · '+((e.reason&&e.reason.stack)||e.reason)));
const nativeLog=console.log.bind(console),nativeErr=console.error.bind(console),nativeWarn=console.warn.bind(console);console.log=(...a)=>{nativeLog(...a);const s=a.map(x=>typeof x==='string'?x:JSON.stringify(x)).join(' ');if(/Boxedwine shutdown/i.test(s)){engineDead=true;status('ENGINE SHUTDOWN · NO WINMUGEN')}if(/Could not load zip file/i.test(s))log('F10.5 FS FAULT · zip requested before it landed on the emscripten FS');if(/wine|mugen|jit|wasm|emulator|error|warn|root|mount|running|fps|frame/i.test(s))log('BW OUT · '+s.slice(0,1200))};console.error=(...a)=>{nativeErr(...a);log('BW ERR · '+a.join(' ').slice(0,1400))};console.warn=(...a)=>{nativeWarn(...a);log('BW WARN · '+a.join(' ').slice(0,1200))};
function ensure(id,tag='div',type=''){let e=document.getElementById(id);if(!e){e=document.createElement(tag);e.id=id;if(type)e.type=type;e.style.display='none';document.body.appendChild(e)}return e}['savejitbtn','uploadbtn','downloadbtn','startbtn','openModalExeClick'].forEach(id=>ensure(id,'button'));ensure('upload','input','file');ensure('pointerLock','input','checkbox');ensure('soundToggle','input','checkbox');ensure('showConsole','input','checkbox');ensure('progress','progress');['status','spinner','dropzone','output','sound-checkbox','message','modalLink','modalLinkExe','items','tree','selectedItem','loadStatus','loading','console'].forEach(id=>ensure(id));
const keyMeta={ArrowUp:[38,'ArrowUp'],ArrowDown:[40,'ArrowDown'],ArrowLeft:[37,'ArrowLeft'],ArrowRight:[39,'ArrowRight'],KeyA:[65,'a'],KeyS:[83,'s'],KeyD:[68,'d'],KeyZ:[90,'z'],KeyX:[88,'x'],KeyC:[67,'c'],Enter:[13,'Enter'],Escape:[27,'Escape']};
function emitKey(code,key,down){const m=keyMeta[code]||[0,key||''],type=down?'keydown':'keyup',opts={key:key||m[1],code,keyCode:m[0],which:m[0],bubbles:true,cancelable:true};canvas.focus();for(const target of [canvas,document,window]){try{const ev=new KeyboardEvent(type,opts);try{Object.defineProperty(ev,'keyCode',{get:()=>m[0]});Object.defineProperty(ev,'which',{get:()=>m[0]})}catch(_){}target.dispatchEvent(ev)}catch(_){}}}
function bindPress(el,codes){let held=false;const dn=e=>{e.preventDefault();if(held)return;held=true;el.classList.add('on');codes.forEach(k=>emitKey(k[0],k[1],true))},up=e=>{e.preventDefault();if(!held)return;held=false;el.classList.remove('on');[...codes].reverse().forEach(k=>emitKey(k[0],k[1],false))};el.addEventListener('pointerdown',dn);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);el.addEventListener('pointerleave',e=>{if(held)up(e)})}
document.querySelectorAll('#controls [data-k]').forEach(el=>bindPress(el,[[el.dataset.k,el.dataset.key]]));const macros={UL:[['ArrowUp','ArrowUp'],['ArrowLeft','ArrowLeft']],UR:[['ArrowUp','ArrowUp'],['ArrowRight','ArrowRight']],DL:[['ArrowDown','ArrowDown'],['ArrowLeft','ArrowLeft']],DR:[['ArrowDown','ArrowDown'],['ArrowRight','ArrowRight']],'2P':[['KeyA','a'],['KeyS','s']],'2K':[['KeyZ','z'],['KeyX','x']]};document.querySelectorAll('#controls [data-macro]').forEach(el=>bindPress(el,macros[el.dataset.macro]||[]));
function setControlsHidden(h){controls.classList.toggle('hidden',h);ctrlToggle.textContent=h?'SHOW CTRL':'HIDE CTRL'}ctrlToggle.addEventListener('click',()=>setControlsHidden(!controls.classList.contains('hidden')));function setDebugHidden(h){diagWrap.classList.toggle('hidden',h);debugToggle.textContent=h?'SHOW DEBUG':'HIDE DEBUG'}debugToggle.addEventListener('click',()=>setDebugHidden(!diagWrap.classList.contains('hidden')));diagInlineToggle.addEventListener('click',()=>setDebugHidden(!diagWrap.classList.contains('hidden')));
function u16(v,o){return v.getUint16(o,true)}function u32(v,o){return v.getUint32(o,true)}
async function inspect(file){status('INDEXING ZIP');const tailStart=Math.max(0,file.size-65557),tb=await file.slice(tailStart).arrayBuffer(),tv=new DataView(tb);let e=-1;for(let i=tv.byteLength-22;i>=0;i--){if(u32(tv,i)===0x06054b50){e=i;break}}if(e<0)throw new Error('ZIP end record not found');const cdSize=u32(tv,e+12),cdOffset=u32(tv,e+16),cb=await file.slice(cdOffset,cdOffset+cdSize).arrayBuffer(),cv=new DataView(cb),dec=new TextDecoder();let p=0,entries=[];while(p+46<=cv.byteLength&&u32(cv,p)===0x02014b50){const method=u16(cv,p+10),comp=u32(cv,p+20),uncomp=u32(cv,p+24),fn=u16(cv,p+28),ex=u16(cv,p+30),cm=u16(cv,p+32),local=u32(cv,p+42),name=dec.decode(new Uint8Array(cb,p+46,fn));entries.push({name,method,comp,uncomp,local});p+=46+fn+ex+cm}const exe=entries.find(x=>x.name.toLowerCase()==='winmugen.exe'||x.name.toLowerCase().endsWith('/winmugen.exe'));if(!exe)throw new Error('Winmugen.exe not found');exePath=exe.name;exeDir=exe.name.includes('/')?exe.name.slice(0,exe.name.lastIndexOf('/')):'';const prefix=exeDir?exeDir.replace(/\\/g,'/')+'/':'';function keep(ent){if(!ent.name||ent.name.endsWith('/')||!ent.name.startsWith(prefix))return false;const l=ent.name.slice(prefix.length).toLowerCase();if(l==='winmugen.exe')return true;if(!l.includes('/')&&/\.(dll|ini|cfg|dat|txt)$/i.test(l))return true;const capsule=l.startsWith('chars/mole/')||l.startsWith('chars/g.ken/')||l==='stages/cfjed_warzard.def'||l==='stages/cfjed_warzard.sff';return l.startsWith('data/')||l.startsWith('font/')||l.startsWith('plugins/')||capsule}const chosen=entries.filter(keep),packed=chosen.reduce((a,x)=>a+x.comp,0),plain=chosen.reduce((a,x)=>a+x.uncomp,0);log('F10.5 LEAN PLAN · files='+chosen.length+' · compressed='+(packed/1048576).toFixed(1)+' MB · expanded='+(plain/1048576).toFixed(1)+' MB');return {chosen,prefix}}
async function entryRaw(file,ent){const hb=await file.slice(ent.local,ent.local+30).arrayBuffer(),hv=new DataView(hb);if(u32(hv,0)!==0x04034b50)throw new Error('Bad local ZIP header: '+ent.name);const fn=u16(hv,26),ex=u16(hv,28),start=ent.local+30+fn+ex,pb=await file.slice(start,start+ent.comp).arrayBuffer(),packed=new Uint8Array(pb);if(ent.method===0)return packed;if(ent.method===8)return fflate.inflateSync(packed);throw new Error('Unsupported ZIP method '+ent.method+' for '+ent.name)}
function patchSystem(text){const m=text.match(/\[Select Info\][\s\S]*?(?=\r?\n\s*\[|$)/i);if(!m)return text;let sec=m[0];const set=(key,val)=>{const r=new RegExp('(^\\s*'+key+'\\s*=\\s*).*$','im');sec=r.test(sec)?sec.replace(r,'$1'+val):sec+'\r\n'+key+' = '+val};set('rows','1');set('columns','2');set('showemptyboxes','0');return text.replace(m[0],sec)}
function patchSelect(text){const chars='[Characters]\r\nmole, stages/cfjed_warzard.def\r\nG.Ken, stages/cfjed_warzard.def\r\n',stages='[ExtraStages]\r\nstages/cfjed_warzard.def\r\n';if(!/\[Characters\]/i.test(text))throw new Error('select.def Characters missing');text=text.replace(/\[Characters\][\s\S]*?(?=\r?\n\s*\[|$)/i,chars);text=/\[ExtraStages\]/i.test(text)?text.replace(/\[ExtraStages\][\s\S]*?(?=\r?\n\s*\[|$)/i,stages):text+'\r\n'+stages;return text}
async function buildLeanZip(file){const {chosen,prefix}=await inspect(file);status('BUILDING LEAN JIT ZIP');prep.textContent='Repacking capsule for WASM-JIT…';let chunks=[],resolveZip,rejectZip;const done=new Promise((res,rej)=>{resolveZip=res;rejectZip=rej}),zip=new fflate.Zip((err,data,final)=>{if(err){rejectZip(err);return}chunks.push(data);if(final)resolveZip()});let n=0;for(const ent of chosen){let raw=await entryRaw(file,ent),rel=ent.name.slice(prefix.length).toLowerCase();if(/(^|\/)data\/.*system\.def$/i.test(rel)){let t=new TextDecoder().decode(raw);t=patchSystem(t);raw=new TextEncoder().encode(t);log('F10.5 PATCH · '+ent.name+' · 2x1')}if(rel==='data/select.def'){let t=new TextDecoder().decode(raw);t=patchSelect(t);raw=new TextEncoder().encode(t);log('F10.5 CAPSULE · mole vs G.Ken · cfjed_warzard')}const z=new fflate.ZipDeflate(ent.name,{level:1});zip.add(z);z.push(raw,true);raw=null;n++;if(n===1||n%25===0||n===chosen.length){prep.textContent='Repacking '+n+'/'+chosen.length+'…';log('F10.5 ZIP PROGRESS · '+n+'/'+chosen.length)}await new Promise(r=>setTimeout(r,0))}zip.end();await done;leanBlob=new Blob(chunks,{type:'application/zip'});chunks=null;log('F10.5 LEAN ZIP READY · '+(leanBlob.size/1048576).toFixed(1)+' MB');return leanBlob}
function installFetch(){const nf=window.fetch.bind(window);window.fetch=async function(input,init){const u=typeof input==='string'?input:(input&&input.url)||'';if(u===APP||u.endsWith('/'+APP)){log('F10.5 FETCH · serving in-memory '+APP+' · '+(leanBlob.size/1048576).toFixed(1)+' MB');return new Response(leanBlob,{status:200,headers:{'Content-Type':'application/zip','Content-Length':String(leanBlob.size)}})}if(u.endsWith('userapp-jit-modules.zip'))return new Response('',{status:404});return nf(input,init)}}
function scriptText(t){return new Promise((res,rej)=>{const s=document.createElement('script');s.text=t;s.onerror=rej;document.head.appendChild(s);res()})}function scriptURL(u){return new Promise((res,rej)=>{const s=document.createElement('script');s.src=u;s.onload=res;s.onerror=()=>rej(new Error('Failed '+u));document.head.appendChild(s)})}
function instrument(){try{const p2=CanvasRenderingContext2D&&CanvasRenderingContext2D.prototype,o=p2&&p2.putImageData;if(o&&!o.__f105){p2.putImageData=function(){drawCount++;return o.apply(this,arguments)};p2.putImageData.__f105=1}}catch(_){}try{for(const C of [window.WebGLRenderingContext,window.WebGL2RenderingContext]){if(!C)continue;for(const k of ['drawArrays','drawElements']){const o=C.prototype[k];if(o&&!o.__f105){C.prototype[k]=function(){drawCount++;return o.apply(this,arguments)};C.prototype[k].__f105=1}}}}catch(_){}function raf(){rafCount++;requestAnimationFrame(raf)}requestAnimationFrame(raf);setInterval(()=>{const r=rafCount-rafLast,d=drawCount-drawLast;rafLast=rafCount;drawLast=drawCount;window.F105_PERF='RAF='+r+' DRAW='+d;if(fpsBadge)fpsBadge.textContent='R '+r+' · D '+d;if(engineDead)return;if(d>0){status('WINMUGEN RUNNING · '+d+' FPS')}else if(startedAt&&Date.now()-startedAt>15000&&drawCount===0){status('NO FRAMES YET · SEE TRACE')}},1000)}
async function boot(file){if(bootStarted)return;bootStarted=true;lines=[];try{instrument();await buildLeanZip(file);installFetch();status('LOADING WASM-JIT SHELL');const sr=await fetch(SHELL,{cache:'no-store'});if(!sr.ok)throw new Error('shell HTTP '+sr.status);let ss=await sr.text();ss+='\n;window.__F105_Config=Config;window.__F105_setConfiguration=setConfiguration;window.__F105_start=start;window.__F105_startEmulator=startEmulator;window.__F105_Module=Module;';await scriptText(ss);const cfg=window.__F105_Config;if(!cfg)throw new Error('JIT Config bridge missing');cfg.locateRootBaseUrl='./assets/';cfg.locateAppBaseUrl='';cfg.locateOverlayBaseUrl='https://cdn.jsdelivr.net/gh/andrewnakas/exebrowser@c6049f9684f3c6895c8f31f361a0a29462793f41/public/boxedwine/apps/';cfg.persist_d_drive=false;const prog=exePath.replace(/\\/g,'/'),work='/home/username/.wine/dosdevices/c:/files/'+(exeDir||'');cfg.urlParams='root='+ROOT+'&overlay=wine1.7.55-v8-min-online.zip&app='+APP+'&p='+encodeURIComponent(prog)+'&w='+encodeURIComponent(work)+'&auto=true&sound=false&bpp=16&storage=memory&jit-record=false';log('F10.5 URLPARAMS · '+cfg.urlParams);window.__F105_setConfiguration();if(window.Module){const old=window.Module.locateFile;window.Module.locateFile=(p,prefix)=>p==='boxedwine.wasm'?BASE+'boxedwine.wasm':(old?old(p,prefix):prefix+p)}setup.classList.add('hide');status('LOADING SIMD WASM-JIT');log('F10.5 JIT ENGINE · upstream ba68d801 · SIMD128 JIT · Wine 1.7.55 proven root');await scriptURL(ENGINE);status('WASM-JIT STARTING');startedAt=Date.now();log('F10.5 DEFERRED START · auto=true · shell calls start() after root+overlay+app land on the FS')}catch(e){fail(e)}}
zipInput.addEventListener('change',()=>{const f=zipInput.files&&zipInput.files[0];if(f)boot(f)});copyBtn.addEventListener('click',async()=>{const text='MOBMUGEN · RIG F · F10.5 SIMD WASM-JIT\nRUNTIME STATUS · '+state.textContent+'\nPAGE · '+location.href+'\nUSER AGENT · '+navigator.userAgent+'\n\nTRACE\n'+lines.join('\n')+'\nF10.5 PERF SNAPSHOT · '+(window.F105_PERF||'pending');try{await navigator.clipboard.writeText(text);copyBtn.textContent='COPIED'}catch(_){copyBtn.textContent='COPY FAILED'}setTimeout(()=>copyBtn.textContent='COPY TRACE',1000)});
try{const old=localStorage.getItem(TRACE_KEY);if(old){diag.textContent='RECOVERED PREVIOUS TRACE\n'+old}}catch(_){}
})();
